### ISSUE TITLE
How to set server details

### ISSUE THREAD

**Issue by abuvanth** [mtfaroks/Odoo-JsonRpc-with-ionic3.x#1]
please help me to configure server details

**Comment by CrazyGuo** [comment]
yeah, could you help us to configure server details, that's very good if you do

**Comment by mustafal** [comment]
Yes sure 
Can you please tell me what problem do you face during configure the odoo sever to ionic?

**Comment by CrazyGuo** [comment]
@mtfaroks  @abuvanth 
Thank you,I have test it successfully. 
1. I deploy the odoo 11 on the server as common,nothing special to do.
2. I add the some codes from Odoo-JsonRpc-with-ionic3.x 

At first I tested the ionic app in Chrome ,so it failed. But I tried to build the app to *.apk and installed it in 
my phone,  it successed.....

**Comment by mustafal** [comment]
I have already mentioned in the readme, that this app doesn't work in the chrome browser
