### ISSUE TITLE
only shows white screen on browsers & phones

### ISSUE THREAD

**Issue by MahmoudRamada** [mtfaroks/Odoo-JsonRpc-with-ionic3.x#2]
Drar Mostafa
   i'd build the app on android and iOS and the same 
   for ionic serve did you managed to run this app

**Comment by mustafal** [comment]
can you please tell me how do you run it?
and please see the logs in chrome browser for android, and put logs here.

**Comment by MahmoudRamada** [comment]
Thanks Mostafa (the code is well written) 
the white screen due to sass plugin was not installed correctly 

but i faced another issue with error
ionic can't resolve all parameters for OdooJasonRpc (?,?)
I fixe it by making  odoojasonrpc.ts Injectable like the utils.ts
i don't know if this good or not 

**finally** 
my last issue i'd odoo 9 installed on vps and i'd entered the ip address & tried the site name but
 check url keep giving me an error invalid url

**Comment by mustafal** [comment]
did you put `http://` during call the server?

**Comment by mustafal** [comment]
Your Welcome @MahmoudRamada,
Can you Please tell me on what platform do you run the app?

**Comment by MahmoudRamada** [comment]
i'd tried both http and https form the browser but not tried from android or ios  
but do i have to make an conf. from odoo or the host server apache in my case

**Comment by mustafal** [comment]
this framework does not work with browser. please run it in the android.
