### ISSUE TITLE
Same error on Android check url

### ISSUE THREAD

**Issue by MahmoudRamada** [mtfaroks/Odoo-JsonRpc-with-ionic3.x#3]
Do you use IP or site name ?
I tried from my phone on odoo 9 in production then.
I'd made a fresh odoo 11 installation but still same error invalid url

**Comment by mustafal** [comment]
i use the ip of my PC.
also try release apk first. if it is worked or not in android.

**Comment by quanganh206** [comment]
@mustafal I can make it work, and try to upgrade your code ông ionic v4, but quite straight it not working. Login have strange error with _body isTrustred: true. Do you have any idea about it?

**Comment by mustafal** [comment]
What steps you have did? can you please tell me?

**Comment by quanganh206** [comment]
@mustafal: I just create a new Ionic v4 from scratch and then try to call login method as your Service /web/session/authenticate but in Android I get that kind of error. 

Look like it not a CORS problem, because I can use your demo with that server.

**Comment by mustafal** [comment]
did you run it in the real device or in PC browser?

**Comment by quanganh206** [comment]
I run it on real device, not in browser. Your project work fine with Ionic v3, but when I try with that kind of call in Ionic v4 it through that error. I think v4 webview have problem here.

**Comment by mustafal** [comment]
I think to upgrade this framework to ionic v4.

**Comment by mustafal** [comment]
And Soon I will upgrade it.

**Comment by quanganh206** [comment]
@mustafal: Yes, sure! Now I find cordova-plugin-ionic-webview have some problem. When I try to upgrate cordova-plugin-ionic-webview to ^2.0 it not work and that error show up.
