### ISSUE TITLE
cors problem

### ISSUE THREAD

**Issue by khaled-elrifaay** [mtfaroks/Odoo-JsonRpc-with-ionic3.x#5]
'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
i thinks there is a problem with HttpClient

**Comment by mustafal** [comment]
can you please tell me how did you run this?

**Comment by khaled-developer** [comment]
i used angular 8.1.2 , can you make a new project with ionic 4 , it will help me to know how it will be

**Comment by mustafal** [comment]
you just have to run this project in production mode otherwise it will not work. you have to fire this  command `ionic cordova run android --prod`
